apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - name: http
      port: 80
      targetPort: 80
      
