# configMap - used for non-confidential env variables

apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanaged-dbcreation-script
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webapp;
